theme: jekyll-theme-primer

title: Notes
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
repository: "jastkand/krivko.me"

paginate: 5
paginate_path: "/page/:num/"

permalink: pretty

author:
  name: Andrey Krivko
  twitter: jastkand
  github: jastkand

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true
